workflows:
  android-workflow:
    name: بناء أندرويد - تطبيق البث الرياضي
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: جلب الحزم
        script: flutter pub get
      - name: بناء APK
        script: flutter build apk --release --split-per-abi
    artifacts:
      - build/**/outputs/**/*.apk
